export const SET_LOGIN_MESSAGE = 'SET_LOGIN_MESSAGE';
export const SET_SEARCH_MESSAGE = 'SET_SEARCH_MESSAGE';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_LOGGED = 'SET_LOGGED';
export const SET_FOLLOWING_ARTISTS = 'SET_FOLLOWING_ARTISTS';